#!/bin/bash

DIVINE_MARKUP_RE="<([[:alnum:]]+)(.*)"                           # pmatch[1]=tagname */
DIVINE_IDENT_RE="id=[\"]?([[:alpha:]][-_.[:alnum:]]*)[\"]?"             # pmatch[1] */
DIVINE_IDENT_RE2="^[[:blank:]]*([[:alpha:]][-_.[:alnum:]]+)*[[:blank:]]*([.][[:alpha:]][-_.[:alnum:]]+)"
DIVINE_TEXT_RE="(^|[[:blank:]])+[\"]([^\"]*)[\"]"                      # pmatch[2] */
DIVINE_MACRO_RE="([$])([.[:alpha:]].*)"                                 # pmatch[2] */

WS="[[:blank:]]*"
ATTRIBOUND="[[:blank:]\\\"]"				
STARTBOUND="[[:blank:]]"				# 1 record
ENDBOUND="[[:blank:]]"					# 1 record
KEYWORD="[_[:alpha:]][-_[:alnum:]]*"
UNDEF="[[:print:]]*"

ELMNAME="$KEYWORD"	
ELMID="id=[\\\"]?($KEYWORD)[\\\"]?"
ELMCLASS="class=[\\\"]?($KEYWORD)[\\\"]?"
ELMIDORCLASS="(id|class)=[\\\"]?($KEYWORD)[\\\"]?"
ELMCLOSE=">"

MACROID="[\$]($KEYWORD)"
IDSHORT="$KEYWORD"
CLASSSHORT="[.]($KEYWORD)"
HTMLTAG="<($ELMNAME)[^>]*>"
TEXTQUOTE="[\\\"](.*)[\\\"]"				# 2 records

TARGET_REGEX="^$WS$MACROID?$WS($IDSHORT)?[^.]*$CLASSSHORT?[^<]*($HTMLTAG)?[^\\\"]*($TEXTQUOTE)?.*\$"

TEST_REGEX="$TARGET_REGEX"
#"^$WS($MACROID)?($IDSHORT)?($CLASSSHORT)?"

echo "$TEST_REGEX"
./customgrep test/testsuite.txt "$TEST_REGEX"


